// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf1DT8oL7UfoJMidy0v8XNfX65M578q5M',
    appId: '1:675588274949:web:3d0daf67ae51b54290156c',
    messagingSenderId: '675588274949',
    projectId: 'paper-gen-app-ca4fb',
    authDomain: 'paper-gen-app-ca4fb.firebaseapp.com',
    storageBucket: 'paper-gen-app-ca4fb.firebasestorage.app',
    measurementId: 'G-76JE41E5P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB45GZOOPDk12lq3cw9KUomNCwNWoqujx4',
    appId: '1:675588274949:android:389ebcb03344896390156c',
    messagingSenderId: '675588274949',
    projectId: 'paper-gen-app-ca4fb',
    storageBucket: 'paper-gen-app-ca4fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6TrxudleeximrH3L8-zrq7z3MWeaW9h8',
    appId: '1:675588274949:ios:54c3a22bb8f937ce90156c',
    messagingSenderId: '675588274949',
    projectId: 'paper-gen-app-ca4fb',
    storageBucket: 'paper-gen-app-ca4fb.firebasestorage.app',
    iosClientId: '675588274949-bd848pq5anhbjrfnjg3jd37hrq5np55b.apps.googleusercontent.com',
    iosBundleId: 'com.example.paperGen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6TrxudleeximrH3L8-zrq7z3MWeaW9h8',
    appId: '1:675588274949:ios:54c3a22bb8f937ce90156c',
    messagingSenderId: '675588274949',
    projectId: 'paper-gen-app-ca4fb',
    storageBucket: 'paper-gen-app-ca4fb.firebasestorage.app',
    iosClientId: '675588274949-bd848pq5anhbjrfnjg3jd37hrq5np55b.apps.googleusercontent.com',
    iosBundleId: 'com.example.paperGen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf1DT8oL7UfoJMidy0v8XNfX65M578q5M',
    appId: '1:675588274949:web:7210f4c10a7a647d90156c',
    messagingSenderId: '675588274949',
    projectId: 'paper-gen-app-ca4fb',
    authDomain: 'paper-gen-app-ca4fb.firebaseapp.com',
    storageBucket: 'paper-gen-app-ca4fb.firebasestorage.app',
    measurementId: 'G-8RY2M0TW8S',
  );

}