// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn8pG2e3h9N3Hm3L5icUqJjKmzc2RLSmo',
    appId: '1:72439715330:web:ae9f0050e7b38c0409b91b',
    messagingSenderId: '72439715330',
    projectId: 'paper-gen-97dfd',
    authDomain: 'paper-gen-97dfd.firebaseapp.com',
    storageBucket: 'paper-gen-97dfd.firebasestorage.app',
    measurementId: 'G-M1DWGSDWCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB7KOPI12HCkHCWikAXCagAGs21-EHUGE',
    appId: '1:72439715330:android:fd74945ea5a1d5d409b91b',
    messagingSenderId: '72439715330',
    projectId: 'paper-gen-97dfd',
    storageBucket: 'paper-gen-97dfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDCEc7x5YbLXkbqi4KkBbBbpBKxrUG00U',
    appId: '1:72439715330:ios:8120997b3549fc0609b91b',
    messagingSenderId: '72439715330',
    projectId: 'paper-gen-97dfd',
    storageBucket: 'paper-gen-97dfd.firebasestorage.app',
    iosClientId: '72439715330-mphr25tlu96oq4ssgr600bqcksoal9nm.apps.googleusercontent.com',
    iosBundleId: 'com.example.paperGen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDCEc7x5YbLXkbqi4KkBbBbpBKxrUG00U',
    appId: '1:72439715330:ios:8120997b3549fc0609b91b',
    messagingSenderId: '72439715330',
    projectId: 'paper-gen-97dfd',
    storageBucket: 'paper-gen-97dfd.firebasestorage.app',
    iosClientId: '72439715330-mphr25tlu96oq4ssgr600bqcksoal9nm.apps.googleusercontent.com',
    iosBundleId: 'com.example.paperGen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn8pG2e3h9N3Hm3L5icUqJjKmzc2RLSmo',
    appId: '1:72439715330:web:66d0cf6a4a9e2d0f09b91b',
    messagingSenderId: '72439715330',
    projectId: 'paper-gen-97dfd',
    authDomain: 'paper-gen-97dfd.firebaseapp.com',
    storageBucket: 'paper-gen-97dfd.firebasestorage.app',
    measurementId: 'G-RHB6N3VMVP',
  );
}
